### ISSUE TITLE
Tester only checks one case

### ISSUE THREAD

**Issue by gtklocker** [UoI-CSE-MYY402/lab02_starter#1]
The tester only checks the case for "racecar". It could be far more extensive by injecting more known palindrome and non palindrome strings to the mesg label and checking for the exit code of the program for each of them.

**Comment by efthym** [comment]
I presume people try out different string themselves.

I do have a number of different tests which I run when I mark the submitted work.
They use the same principles as the tester I provide with the starter files: a set of expected values for registers and memory locations (using mips_tester.rb). It requires python (3 I think ) and the Unix sed tool. However given the trouble (tens of emails) to get Ruby running across all platforms students use, I don't want to make it available to all again.
